// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::VNT_ZKP_ELF;
use risc0_zkvm::{default_prover, ExecutorEnv};

use clap::Parser;
use tokio_postgres::{Client, Error};

use std::{collections::HashMap, fs, path::Path, time::Instant};

use tracing::{error, info};
use tracing_appender::rolling;
use tracing_subscriber::fmt::layer;
use tracing_subscriber::prelude::*;

use core::{log, postgres::Postgres, AggregationJournal, AggregationPrivateInput, CLog, Log};

mod db;

#[derive(Parser, Debug)]
#[clap(author, version, about, long_about = None)]
struct Args {
    /// Log directory
    #[clap(long, default_value = "logs")]
    logdir: String,

    /// Log file name
    #[clap(long, default_value = "aggregation_prover")]
    logfile: String,

    /// Log level
    #[clap(long, default_value = "INFO")]
    logfilter: String,

    /// Receipt directory
    #[clap(long, default_value = "receipts")]
    receiptdir: String,

    /// Output file path to save the receipt.
    #[clap(
        short = 'r',
        long,
        value_parser,
        default_value = "aggregation_receipt.bin"
    )]
    receiptfile: String,

    /// Total count of internal nodes
    #[clap(short = 'n', long, value_parser, default_value_t = 10, value_parser = clap::value_parser!(i32).range(1..=10))]
    tables: i32,
}

#[tokio::main]
async fn main() -> Result<(), Error> {
    let args = Args::parse();

    let logfilter = log::get_log_level(&args.logfilter);
    let logdir = Path::new(".").join(&args.logdir);
    std::fs::create_dir_all(&logdir).expect("Failed to create log directory");

    let file_appender = rolling::daily(logdir, &args.logfile);
    let (non_blocking, log_guard) = tracing_appender::non_blocking(file_appender);

    let logger = layer()
        .with_writer(non_blocking)
        .with_ansi(false)
        .compact()
        .with_filter(logfilter);

    tracing_subscriber::registry().with(logger).init();

    /*
     * Preparing inputs by reading database
     */

    let postgres = Postgres::new();
    let pg_client = postgres
        .connect()
        .await
        .expect("Failed to connect to Postgres");

    let start = Instant::now();

    info!("Starting aggregation prover");

    /*
     * 1. Check if there are new logs to process
     * 2. Read all logs from database
     */
    let prev_seq = db::get_metadata(&pg_client, "last_seq").await;
    let curr_seq = db::get_curr_seq(&pg_client).await;

    if curr_seq < prev_seq {
        info!("No new logs to process, exiting.");
        return Ok(());
    }

    info!(
        "Previous sequence number: {}, Current sequence number: {}",
        prev_seq, curr_seq
    );

    let mut logs: Vec<Vec<Log>> = Vec::new();
    let num_tables = args.tables;

    for i in 0..num_tables {
        let table_logs = db::get_logs(&pg_client, i).await;
        logs.push(table_logs);
        info!(
            "Fetched {} logs from table {}",
            logs.last().unwrap().len(),
            i
        );
    }
    info!(
        "Total logs fetched from all tables: {}",
        logs.iter().map(|l| l.len()).sum::<usize>()
    );

    // Fetch all logs that were written (inserted or updated) since the last sequence number.
    let new_logs = db::get_new_logs(&pg_client, &args.tables, &prev_seq, &curr_seq).await;
    assert!(new_logs.len() != 0, "No logs found to process");

    let aggregated_new_clogs = aggregate_logs(&new_logs);

    let upserted_indices = upsert_clogs(&pg_client, &aggregated_new_clogs).await;
    info!(
        "Updated Merkle tree indices: {}",
        upserted_indices
            .iter()
            .map(|n| n.to_string())
            .collect::<Vec<String>>()
            .join(", ")
    );

    // Update the last sequence number in the database metadata
    db::put_metadata(&pg_client, "last_seq", curr_seq).await;
    info!("Updated last_seq in DB metadata to {}", curr_seq);

    let clogs = db::get_clogs(&pg_client).await;

    let input = AggregationPrivateInput {
        logs: logs,                      // All the logs from each nodes: Vec<Vec<Log>>
        new_clogs: aggregated_new_clogs, // New logs in hashmap key by flow_id: HashMap<i32, CLog>
        clogs: clogs,                    // Entire CLog table: Vec<CLog>
    };

    /*
     * Proof generation
     */

    let env = ExecutorEnv::builder()
        .write(&input)
        .unwrap()
        .build()
        .unwrap();

    // Obtain the default prover.
    let prover = default_prover();

    // Proof information by proving the specified ELF binary.
    // This struct contains the receipt along with statistics about execution of the guest
    let prove_info = prover.prove(env, VNT_ZKP_ELF).unwrap();

    /*
     * Receipt file output
     */

    // Extract the receipt.
    let receipt = prove_info.receipt;

    let journal: AggregationJournal = receipt.journal.decode().expect("Journal decoding failed");
    if !journal.success {
        error!("Aggregation failed: {}", journal.message);
        return Ok(());
    }

    // Output receipt to file
    let receiptdir = Path::new(".").join(&args.receiptdir);
    std::fs::create_dir_all(&receiptdir).expect("Failed to create log directory");

    let encoded_receipt = bincode::serialize(&receipt).unwrap();
    let receiptfile = receiptdir.join(&args.receiptfile);
    fs::write(&receiptfile, encoded_receipt).expect("Failed to write receipt");

    info!("Receipt wrote to {}", receiptfile.display());

    info!(
        "Aggregation prover completed in {:.2?} sec",
        start.elapsed().as_secs()
    );

    // Make sure all logs are dropped.
    drop(log_guard);

    Ok(())
}

/**
 * Aggregates new logs from all nodes into a single HashMap where the key is the flow_id.
 * The CLog struct is used to represent the aggregated log.
 */
fn aggregate_logs(new_logs: &Vec<Vec<Log>>) -> HashMap<i32 /* flow_id */, CLog> {
    let mut aggregated_map = HashMap::<i32, CLog>::new();

    for logs in new_logs {
        for log in logs {
            let key = log.flow_id;

            // If key exists, modify it; otherwise, insert a new value
            aggregated_map
                .entry(key)
                .and_modify(|clog: &mut CLog| clog.hop_cnt += log.hop_cnt)
                .or_insert(CLog::from_log(&log));
        }
    }

    aggregated_map
}

/**
 * Upserts the aggregated logs into the central logs table and returns the indices of the
 * Merkle tree entries that were updated.
 */
async fn upsert_clogs(client: &Client, diff: &HashMap<i32, CLog>) -> Vec<i32> {
    let mut merkle_tree_idxs = Vec::new();

    // UPSERT aggregated logs into central logs table
    for entry in diff {
        let clog = entry.1;

        match db::upsert_clog(&client, &clog).await {
            Ok(idx) => {
                if idx >= 0 {
                    merkle_tree_idxs.push(idx);
                }
            }
            Err(err) => {
                error!("Failed to upsert clog: {}", err);
            }
        };
    }

    merkle_tree_idxs
}
