// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::VNT_ZKP_ELF;
use risc0_zkvm::{default_prover, ExecutorEnv, ProverOpts, Receipt};

use clap::Parser;
use tokio_postgres::Error;

use std::{collections::HashMap, fs, path::Path, time::Instant};

use tracing::{error, info};
use tracing_appender::rolling;
use tracing_subscriber::fmt::layer;
use tracing_subscriber::prelude::*;

use core::{
    log,
    merkle::MerkleTree as CLogMerkleTree,
    postgres::Postgres,
    util,
    AggregationJournal,
    AggregationPrivateInput,
    CLog,
    Log,
};

mod db;

#[derive(Parser, Debug)]
#[clap(author, version, about, long_about = None)]
struct Args {
    /// Log directory
    #[clap(long, default_value = "logs")]
    logdir: String,

    /// Log file name
    #[clap(long, default_value = "aggregation_prover")]
    logfile: String,

    /// Log level
    #[clap(long, default_value = "INFO")]
    logfilter: String,

    /// Receipt directory
    #[clap(long, default_value = "receipts")]
    receiptdir: String,

    /// Output file path to save the receipt.
    #[clap(
        short = 'r',
        long,
        value_parser,
        default_value = "aggregation_receipt.bin"
    )]
    receiptfile: String,

    /// Total count of internal nodes
    #[clap(short = 'n', long, value_parser, default_value_t = 10, value_parser = clap::value_parser!(i32).range(1..=10))]
    tables: i32,
}

#[tokio::main]
async fn main() -> Result<(), Error> {
    let args = Args::parse();

    let logfilter = log::get_log_level(&args.logfilter);
    let logdir = Path::new(".").join(&args.logdir);
    std::fs::create_dir_all(&logdir).expect("Failed to create log directory");

    let file_appender = rolling::daily(logdir, &args.logfile);
    let (non_blocking, log_guard) = tracing_appender::non_blocking(file_appender);

    let logger = layer()
        .with_writer(non_blocking)
        .with_ansi(false)
        .compact()
        .with_filter(logfilter);

    tracing_subscriber::registry().with(logger).init();

    /*
     * Preparing inputs by reading database
     */

    let postgres = Postgres::new();
    let pg_client = postgres
        .connect()
        .await
        .expect("Failed to connect to Postgres");

    info!("Starting aggregation prover");

    // Read previous merkle tree
    let receiptdir = Path::new(".").join(&args.receiptdir);
    let aggregation_receiptfile = receiptdir.join(&args.receiptfile);

    let merkle_tree: CLogMerkleTree<CLog>;
    if receiptdir.exists() && aggregation_receiptfile.exists() {
        let aggregation_receipt: Receipt =
            bincode::deserialize(&fs::read(&aggregation_receiptfile).unwrap()).unwrap();

        let aggregation_journal: AggregationJournal = aggregation_receipt.journal.decode().unwrap();
        merkle_tree = util::deserialize_merkle_tree(&aggregation_journal.tree);
        info!(
            "Loaded previous Merkle tree with {} leaves",
            merkle_tree.leaves_len()
        );
    } else {
        merkle_tree = CLogMerkleTree::new(Vec::new());
        info!("No previous Merkle tree found, starting fresh");
    }

    /*
     * 1. Check if there are new logs to process
     * 2. Read all logs and hashes from database
     * 3. Read all new logs that were written since the last sequence number
     * 4. Calculate the diff between the aggregation of new logs and the existing CLogs
     */

    let prev_seq = db::get_metadata(&pg_client, "last_seq").await;
    info!("Processing new logs from seq > {}", prev_seq);

    // Read all logs and hashes from database
    let mut logs: Vec<Vec<Log>> = Vec::new();
    let mut hashes: Vec<[u8; 32]> = Vec::new();
    let num_tables = args.tables;

    let hash_round = db::get_metadata(&pg_client, "last_logs_hash_round").await as i32;

    for i in 0..num_tables {
        let table_logs = db::get_logs(&pg_client, i).await;
        logs.push(table_logs);
        info!(
            "Fetched {} logs from table {}",
            logs.last().unwrap().len(),
            i
        );

        let table_hash = db::get_hash(&pg_client, i, hash_round).await;
        hashes.push(table_hash);
    }
    info!(
        "Total logs fetched from all tables: {}",
        logs.iter().map(|l| l.len()).sum::<usize>()
    );

    // Read all new logs that were written since the last sequence number
    let new_logs = db::get_new_logs(&pg_client, &args.tables, &prev_seq).await;
    assert!(new_logs.len() != 0, "No logs found to process");

    // Calculate the CLogs to insert or update (without the ids yet)
    let diff_clogs = aggregate_logs(&new_logs);

    // Must get before upsert
    let old_clogs: Vec<CLog> = db::get_clogs(&pg_client).await;
    let old_clogs_map: HashMap<i32 /* flow_id */, CLog> = old_clogs
        .iter()
        .map(|clog| (clog.flow_id, clog.clone()))
        .collect();

    // Distinguish the updates and inserts by checking the old clogs table.
    // If it exists, we update. If not, we insert and use the id as clog.id.
    // We DO NOT use the clog.id as the id. It's assigned during the database inserts.
    let mut update_clogs: HashMap<i32 /* flow_id */, CLog> = diff_clogs
        .iter()
        .filter(|(flow_id, _clog)| old_clogs_map.contains_key(flow_id))
        .map(|(flow_id, clog)| (*flow_id, clog.clone()))
        .collect();
    let mut insert_clogs: HashMap<i32 /* flow_id */, CLog> = diff_clogs
        .iter()
        .filter(|(flow_id, _clog)| !old_clogs_map.contains_key(flow_id))
        .map(|(flow_id, clog)| (*flow_id, clog.clone()))
        .collect();
    // Check if update_clogs + insert_clogs = diff_clogs
    assert!(
        update_clogs.len() + insert_clogs.len() == diff_clogs.len(),
        "Update + Insert clog count mismatch"
    );
    assert!(
        diff_clogs.keys().all(|flow_id| {
            update_clogs.contains_key(flow_id) || insert_clogs.contains_key(flow_id)
        }),
        "Diff clogs keys mismatch"
    );
    // Update keys don't contain Insert keys
    assert!(
        update_clogs
            .keys()
            .all(|flow_id| !insert_clogs.contains_key(flow_id)),
        "Update clogs contain insert clog keys"
    );

    info!("Old CLogs:");
    for clog in old_clogs.iter() {
        info!("  {}", clog.to_string());
    }

    /*
     * Update database with new aggregated CLogs
     */
    for (_flow_id, clog) in update_clogs.iter_mut() {
        let id = db::update_aggregate_clog(&pg_client, &clog).await;
        clog.id = id;
    }
    for (_flow_id, clog) in insert_clogs.iter_mut() {
        let id = db::insert_clog(&pg_client, &clog).await;
        clog.id = id;
    }

    info!("Update CLogs:");
    for clog in update_clogs.values() {
        info!("  {}", clog.to_string());
    }
    info!("Insert CLogs:");
    for clog in insert_clogs.values() {
        info!("  {}", clog.to_string());
    }

    // Update the last sequence number in the database metadata
    let curr_seq = db::get_curr_seq(&pg_client).await;
    db::put_metadata(&pg_client, "last_seq", curr_seq).await;
    info!("Updated last_seq in DB metadata to {}", curr_seq);

    let new_clogs: Vec<CLog> = db::get_clogs(&pg_client).await;
    let new_clogs_map: HashMap<i32 /* flow_id */, CLog> = new_clogs
        .iter()
        .map(|clog| (clog.flow_id, clog.clone()))
        .collect();

    info!("New CLogs:");
    for clog in new_clogs.iter() {
        info!("  {}", clog.to_string());
    }

    // Check if the new clogs contain the match of update_clogs and exact match of insert_clogs
    assert!(
        update_clogs.iter().all(|(flow_id, clog)| {
            new_clogs_map.contains_key(flow_id) && new_clogs_map.get(flow_id).unwrap().id == clog.id
        }),
        "Updated clogs not found in new clogs"
    );
    assert!(
        insert_clogs.iter().all(|(flow_id, clog)| {
            new_clogs_map.contains_key(flow_id) && new_clogs_map.get(flow_id).unwrap() == clog
        }),
        "Inserted clogs not found in new clogs"
    );

    let serialized_tree = util::serialize_merkle_tree(&merkle_tree);
    if merkle_tree.leaves_len() != 0 {
        let deserialized = util::deserialize_merkle_tree(&serialized_tree);
        assert!(
            merkle_tree.root() == deserialized.root(),
            "Merkle tree serialization/deserialization failed"
        );
    }

    let input = AggregationPrivateInput {
        logs: logs,                 // All the logs from each nodes: Vec<Vec<Log>>
        hashes: hashes,             // All the hashes for logs table: Vec<[u8; 32]>
        new_logs: new_logs,         // New logs since last seq: Vec<Vec<Log>>
        update_clogs: update_clogs, //
        insert_clogs: insert_clogs, //
        old_clogs: old_clogs_map,   // Old CLogs before update
        new_clogs: new_clogs_map,   // New CLogs after update
        tree: serialized_tree,      // Previous Merkle tree: Vec<u8>
    };

    /*
     * Proof generation
     */

    let env = ExecutorEnv::builder()
        .write(&input)
        .unwrap()
        .build()
        .unwrap();

    // Obtain the default prover.
    let prover = default_prover();
    let opts = ProverOpts::groth16();

    let start = Instant::now();
    let prove_info = prover.prove_with_opts(env, VNT_ZKP_ELF, &opts).unwrap();
    let elapsed = start.elapsed().as_millis();

    /*
     * Receipt file output
     */

    // Extract the receipt.
    let receipt = prove_info.receipt;

    let journal: AggregationJournal = receipt.journal.decode().expect("Journal decoding failed");
    if !journal.success {
        error!("Aggregation failed: {}", journal.message);
        return Ok(());
    }

    // Output receipt to file
    std::fs::create_dir_all(&receiptdir).expect("Failed to create log directory");

    let encoded_receipt = bincode::serialize(&receipt).unwrap();
    let receiptfile = receiptdir.join(&args.receiptfile);
    fs::write(&receiptfile, encoded_receipt).expect("Failed to write receipt");

    info!("Receipt wrote to {}", receiptfile.display());

    info!("Journal size: {} bytes", receipt.journal.bytes.len());
    info!("Seal size: {} bytes", receipt.seal_size());

    info!("Execution took {} ms", elapsed);

    // Make sure all logs are dropped.
    drop(log_guard);

    Ok(())
}

/**
 * Aggregates logs from all nodes into a single HashMap where the key is the flow_id.
 * The CLog struct is used to represent the aggregated log.
 */
fn aggregate_logs(new_logs: &Vec<Vec<Log>>) -> HashMap<i32 /* flow_id */, CLog> {
    let mut aggregated_map = HashMap::<i32, CLog>::new();

    for logs in new_logs {
        for log in logs {
            let key = log.flow_id;

            // If key exists, modify it; otherwise, insert a new value
            aggregated_map
                .entry(key)
                .and_modify(|clog: &mut CLog| clog.hop_cnt += log.hop_cnt)
                .or_insert(CLog::from_log(&log));
        }
    }

    aggregated_map
}
