// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::VNT_ZKP_ELF;
use risc0_zkvm::{default_prover, ExecutorEnv, ProverOpts, Receipt};

use clap::Parser;
use rs_merkle::{algorithms, MerkleTree};
use tokio_postgres::{Client, Error};

use std::{collections::HashMap, fs, path::Path, time::Instant};

use tracing::{error, info};
use tracing_appender::rolling;
use tracing_subscriber::fmt::layer;
use tracing_subscriber::prelude::*;

use core::{log, postgres::Postgres, util, AggregationJournal, AggregationPrivateInput, CLog, Log};

mod db;

#[derive(Parser, Debug)]
#[clap(author, version, about, long_about = None)]
struct Args {
    /// Log directory
    #[clap(long, default_value = "logs")]
    logdir: String,

    /// Log file name
    #[clap(long, default_value = "aggregation_prover")]
    logfile: String,

    /// Log level
    #[clap(long, default_value = "INFO")]
    logfilter: String,

    /// Receipt directory
    #[clap(long, default_value = "receipts")]
    receiptdir: String,

    /// Output file path to save the receipt.
    #[clap(
        short = 'r',
        long,
        value_parser,
        default_value = "aggregation_receipt.bin"
    )]
    receiptfile: String,

    /// Total count of internal nodes
    #[clap(short = 'n', long, value_parser, default_value_t = 10, value_parser = clap::value_parser!(i32).range(1..=10))]
    tables: i32,
}

#[tokio::main]
async fn main() -> Result<(), Error> {
    let args = Args::parse();

    let logfilter = log::get_log_level(&args.logfilter);
    let logdir = Path::new(".").join(&args.logdir);
    std::fs::create_dir_all(&logdir).expect("Failed to create log directory");

    let file_appender = rolling::daily(logdir, &args.logfile);
    let (non_blocking, log_guard) = tracing_appender::non_blocking(file_appender);

    let logger = layer()
        .with_writer(non_blocking)
        .with_ansi(false)
        .compact()
        .with_filter(logfilter);

    tracing_subscriber::registry().with(logger).init();

    /*
     * Preparing inputs by reading database
     */

    let postgres = Postgres::new();
    let pg_client = postgres
        .connect()
        .await
        .expect("Failed to connect to Postgres");

    info!("Starting aggregation prover");

    // Read previous merkle tree
    let receiptdir = Path::new(".").join(&args.receiptdir);
    let aggregation_receiptfile = receiptdir.join(&args.receiptfile);

    let merkle_tree: MerkleTree<algorithms::Sha256>;
    if receiptdir.exists() && aggregation_receiptfile.exists() {
        let aggregation_receipt: Receipt =
            bincode::deserialize(&fs::read(&aggregation_receiptfile).unwrap()).unwrap();

        let aggregation_journal: AggregationJournal = aggregation_receipt.journal.decode().unwrap();
        merkle_tree = util::deserialize_merkle_tree(&aggregation_journal.tree);
        info!(
            "Loaded previous Merkle tree with {} leaves",
            merkle_tree.leaves_len()
        );
    } else {
        merkle_tree = MerkleTree::new();
        info!("No previous Merkle tree found, starting fresh");
    }

    /*
     * 1. Check if there are new logs to process
     * 2. Read all logs and hashes from database
     * 3. Read all new logs that were written since the last sequence number
     * 4. Calculate the diff between the aggregation of new logs and the existing CLogs
     */

    let prev_seq = db::get_metadata(&pg_client, "last_seq").await;
    info!("Processing new logs from seq > {}", prev_seq);

    // Read all logs and hashes from database
    let mut logs: Vec<Vec<Log>> = Vec::new();
    let mut hashes: Vec<[u8; 32]> = Vec::new();
    let num_tables = args.tables;

    let hash_round = db::get_metadata(&pg_client, "last_logs_hash_round").await as i32;

    for i in 0..num_tables {
        let table_logs = db::get_logs(&pg_client, i).await;
        logs.push(table_logs);
        info!(
            "Fetched {} logs from table {}",
            logs.last().unwrap().len(),
            i
        );

        let table_hash = db::get_hash(&pg_client, i, hash_round).await;
        hashes.push(table_hash);
    }
    info!(
        "Total logs fetched from all tables: {}",
        logs.iter().map(|l| l.len()).sum::<usize>()
    );

    // Read all new logs that were written since the last sequence number
    let new_logs = db::get_new_logs(&pg_client, &args.tables, &prev_seq).await;
    assert!(new_logs.len() != 0, "No logs found to process");

    // Calculate the CLogs to insert or update (without the ids yet)
    let mut diff_clogs = aggregate_logs(&new_logs);

    // Must get before upsert
    let old_clogs: Vec<CLog> = db::get_clogs(&pg_client).await;

    // TODO: Technically, upserting should happen only when the aggregation is
    // verified. We could achieve this by having an indirection layer as discussed
    // in the design doc. However, since this is a PoC version, we will do the upsert
    // which also handles the indirection layer. Remember that the CLog.id is the index
    // of the merkle tree + 1.
    //
    // Update or insert the aggregated CLogs into the database.
    // This will give us the indices in the Merkle tree (i.e., indirection layer).
    let upserted_indices = upsert_clogs(&pg_client, &diff_clogs).await;
    info!(
        "Updating Merkle tree indices: {}",
        upserted_indices
            .values()
            .map(|n| n.to_string())
            .collect::<Vec<String>>()
            .join(", ")
    );
    assert!(
        upserted_indices.len() == diff_clogs.len(),
        "Upserted indices count mismatch"
    );

    for (flow_id, id) in &upserted_indices {
        diff_clogs.get_mut(&flow_id).unwrap().id = *id;
        info!("flow_id {} -> clog.id {}", flow_id, *id);
    }

    // Update the last sequence number in the database metadata
    let curr_seq = db::get_curr_seq(&pg_client).await;
    db::put_metadata(&pg_client, "last_seq", curr_seq).await;
    info!("Updated last_seq in DB metadata to {}", curr_seq);

    let new_clogs: Vec<CLog> = db::get_clogs(&pg_client).await;

    // Since we have the upserted_indices, we can use them to get the old and new clogs for the
    // diff. We just need to compare the clog.id with the upserted_indices values.

    let serialized_tree = util::serialize_merkle_tree(&merkle_tree);

    let input = AggregationPrivateInput {
        logs: logs,                         // All the logs from each nodes: Vec<Vec<Log>>
        hashes: hashes,                     // All the hashes for logs table: Vec<[u8; 32]>
        new_logs: new_logs,                 // New logs since last seq: Vec<Vec<Log>>
        upserted_indices: upserted_indices, // Upserted indexes in the Merkle tree: HashMap<i32, i32>
        diff_clogs: diff_clogs,             // Aggregated CLogs to be updated: HashMap<i32, CLog>
        old_clogs: old_clogs,               // Old CLogs before update: Vec<CLog>
        new_clogs: new_clogs,               // New CLogs after update: Vec<CLog>
        tree: serialized_tree,              // Previous Merkle tree: Vec<u8>
    };

    /*
     * Proof generation
     */

    let env = ExecutorEnv::builder()
        .write(&input)
        .unwrap()
        .build()
        .unwrap();

    // Obtain the default prover.
    let prover = default_prover();
    let opts = ProverOpts::groth16();

    let start = Instant::now();
    let prove_info = prover.prove_with_opts(env, VNT_ZKP_ELF, &opts).unwrap();
    let elapsed = start.elapsed().as_millis();

    /*
     * Receipt file output
     */

    // Extract the receipt.
    let receipt = prove_info.receipt;

    let journal: AggregationJournal = receipt.journal.decode().expect("Journal decoding failed");
    if !journal.success {
        error!("Aggregation failed: {}", journal.message);
        return Ok(());
    }

    // Output receipt to file
    std::fs::create_dir_all(&receiptdir).expect("Failed to create log directory");

    let encoded_receipt = bincode::serialize(&receipt).unwrap();
    let receiptfile = receiptdir.join(&args.receiptfile);
    fs::write(&receiptfile, encoded_receipt).expect("Failed to write receipt");

    info!("Receipt wrote to {}", receiptfile.display());

    info!("Journal size: {} bytes", receipt.journal.bytes.len());
    info!("Seal size: {} bytes", receipt.seal_size());

    info!("Execution took {} ms", elapsed);

    // Make sure all logs are dropped.
    drop(log_guard);

    Ok(())
}

/**
 * Aggregates logs from all nodes into a single HashMap where the key is the flow_id.
 * The CLog struct is used to represent the aggregated log.
 */
fn aggregate_logs(new_logs: &Vec<Vec<Log>>) -> HashMap<i32 /* flow_id */, CLog> {
    let mut aggregated_map = HashMap::<i32, CLog>::new();

    for logs in new_logs {
        for log in logs {
            let key = log.flow_id;

            // If key exists, modify it; otherwise, insert a new value
            aggregated_map
                .entry(key)
                .and_modify(|clog: &mut CLog| clog.hop_cnt += log.hop_cnt)
                .or_insert(CLog::from_log(&log));
        }
    }

    aggregated_map
}

/**
 * Upserts the aggregated logs into the central logs table and returns the indices of the
 * Merkle tree entries that were updated.
 */
async fn upsert_clogs(
    client: &Client,
    diff: &HashMap<i32, CLog>,
) -> HashMap<i32 /* flow_id */, i32 /* id */> {
    let mut ids = HashMap::new();

    // UPSERT aggregated logs into central logs table
    for entry in diff {
        let clog = entry.1;

        match db::upsert_clog(&client, &clog).await {
            Ok(id) => {
                if id >= 0 {
                    ids.insert(clog.flow_id, id);
                    info!("Upserted clog for id {}, flow_id {}", id, clog.flow_id);
                }
            }
            Err(err) => {
                error!("Failed to upsert clog: {}", err);
            }
        };
    }

    ids
}

