[package]
name = "core"
version = "0.1.0"
edition = "2021"

[lib]
name = "core"
path = "src/lib.rs"

[dependencies]
# env
dotenv = { workspace = true, optional = true }
serde = { workspace = true }

# postgres
tokio = { workspace = true, optional = true }
tokio-postgres = { workspace = true, optional = true }

# log
tracing = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }
tracing-appender = { workspace = true, optional = true }

rs_merkle = { workspace = true, optional = true }
bincode = { workspace = true, optional = true }

[features]
default = [
  "dep:dotenv",
  "dep:tracing",
  "dep:tracing-subscriber",
  "dep:tracing-appender",
  "dep:rs_merkle",
  "dep:bincode",
]
host = [
  "dep:tokio",
  "dep:tokio-postgres",
]
guest = []
verify = []
simulator = []
query_host = [
  "dep:tokio",
  "dep:tokio-postgres",
]
query_guest = []
query_verify = []
