[package]
name = "query_method"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../../core", features = ["query_guest"] }
risc0-zkvm = { version = "^3.0", default-features = false, features = ['std'] }
zk = { path = "../../zk" }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
bincode = { workspace = true }
hex = { workspace = true }
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.6-risczero.0" }

# nova-snark = { workspace = true }
# ff = { workspace = true }

#core = { path = "../../core", features = ["guest"]}
