[package]
name = "verify"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../core" , features = ["verify"]}

bincode = { workspace = true }
clap = { workspace = true }
nova-snark = { workspace = true }
ff = { workspace = true }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }

zk = { path = "../zk" }
