[package]
name = "verify"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
core = { path = "../core" , features = ["verify"]}

bincode = { workspace = true }
clap = { workspace = true }
risc0-zkvm = { workspace = true }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
