[package]
name = "query_host"
version = "0.1.0"
edition = "2021"

[dependencies]
query_methods = { path = "../query_methods" }
methods = { path = "../methods" }
risc0-zkvm = { version = "^2.1.0" }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }

serde = { workspace = true }
clap = { workspace = true }
bincode = { workspace = true }
tokio = { workspace = true }
tokio-postgres = { workspace = true }
rs_merkle = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }

core = { path = "../core" , features = ["query_host"]}
